name: ci
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-cache

      - name: Get dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/mattn/goveralls@latest
          go get -v -t -d ./...

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          export GO111MODULE=on
          export GOPATH=`go env --json | jq -r .GOPATH`
          go install golang.org/x/tools/cmd/goimports@latest
          go test -v -cover ./...
          goveralls -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2

  build-test:
    name: Build test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build for test
        run: go build
