name: ci
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  setup:
    name: Setup for Go ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-cache

      - name: Get dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go get -v -t -d ./...

  test:
    name: Test in Go ${{ matrix.version }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go test -v ./... -v

  lint:
    name: Lint in Go ${{ matrix.version }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2

  build-test:
    name: Build test in Go ${{ matrix.version }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build for test
        run: go build
