name: Create Tag For Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

env:
  VERSION: v${{ github.event.inputs.version }}

jobs:
  create_tag:
    runs-on: ubuntu-latest
    name: CreateTagForRelease
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          git tag ${env.VERSION}
          git push origin ${env.VERSION}