name: Release

on:
  push:
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - 'README.ja.md'
      - '.gitignore'
      - '.github/workflows/**'

env:
  GO_VERSION: 1.20

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
