name: Release

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'main'

env:
  GO_VERSION: 1.17

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create Tag
        run: |
          VERSION=v`go run main.go --version`
          git tag $VERSION
          git push origin $VERSION

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
